### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 2000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "60214164a3a8489182cde11771a76e62",
  "accountNumber": "1000000001",
  "amount": 1000
}

### query transaction
GET http://localhost:8080/transaction/60214164a3a8489182cde11771a76e62